/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0eoBKQpjmc5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Prata } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function BlogHome() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 shadow">
        <div className="container mx-auto flex justify-between items-center">
          <Link href="#" className="text-2xl font-bold" prefetch={false}>
            My Blog
          </Link>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Tech
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Design
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Business
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  About
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 my-8">
        <main className="col-span-2 space-y-8">
          <article className="flex space-x-6">
            <img
              src="/placeholder.svg"
              alt="Blog Post Thumbnail"
              width={200}
              height={150}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "200/150", objectFit: "cover" }}
            />
            <div>
              <Link href="#" className="text-2xl font-bold hover:text-accent" prefetch={false}>
                The Future of Web Development
              </Link>
              <p className="text-muted-foreground mt-2">
                Explore the latest trends and technologies shaping the future of web development.
              </p>
              <div className="text-xs text-muted-foreground mt-2">Published on May 1, 2023</div>
            </div>
          </article>
          <article className="flex space-x-6">
            <img
              src="/placeholder.svg"
              alt="Blog Post Thumbnail"
              width={200}
              height={150}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "200/150", objectFit: "cover" }}
            />
            <div>
              <Link href="#" className="text-2xl font-bold hover:text-accent" prefetch={false}>
                Designing for Accessibility
              </Link>
              <p className="text-muted-foreground mt-2">
                Learn how to create inclusive and accessible designs for all users.
              </p>
              <div className="text-xs text-muted-foreground mt-2">Published on April 15, 2023</div>
            </div>
          </article>
          <article className="flex space-x-6">
            <img
              src="/placeholder.svg"
              alt="Blog Post Thumbnail"
              width={200}
              height={150}
              className="rounded-lg object-cover"
              style={{ aspectRatio: "200/150", objectFit: "cover" }}
            />
            <div>
              <Link href="#" className="text-2xl font-bold hover:text-accent" prefetch={false}>
                Building a Successful Startup
              </Link>
              <p className="text-muted-foreground mt-2">
                Discover the key strategies and insights for building a thriving startup.
              </p>
              <div className="text-xs text-muted-foreground mt-2">Published on March 30, 2023</div>
            </div>
          </article>
        </main>
        <aside className="space-y-8">
          <div>
            <h3 className="text-lg font-bold mb-4">Popular Posts</h3>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  The Rise of Artificial Intelligence
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Mastering React.js for Web Development
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Branding Strategies for Small Businesses
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">Categories</h3>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Tech
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Design
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:text-accent" prefetch={false}>
                  Business
                </Link>
              </li>
            </ul>
          </div>
        </aside>
      </div>
      <footer className="bg-muted text-muted-foreground py-4 mt-auto">
        <div className="container mx-auto text-center">&copy; 2023 My Blog. All rights reserved.</div>
      </footer>
    </div>
  )
}
