/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GlGKNnb4c11
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function SitecoreDoc() {
  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-white shadow">
        <div className="container mx-auto flex items-center justify-between py-4 px-6">
          <div className="flex items-center space-x-4">
            <img src="/placeholder.svg" alt="Sitecore" className="h-8" />
            <h1 className="text-2xl font-bold">Sitecore Documentation</h1>
          </div>
          <nav className="flex items-center space-x-6">
            <Link href="#" className="text-gray-700" prefetch={false}>
              Products
            </Link>
            <Link href="#" className="text-gray-700" prefetch={false}>
              Resources
            </Link>
            <Link href="#" className="text-gray-700" prefetch={false}>
              Users
            </Link>
            <div className="relative">
              <button className="text-gray-700">
                Developers
                <ChevronDownIcon className="ml-1 w-4 h-4 inline-block" />
              </button>
              <div className="absolute mt-2 w-48 bg-white shadow-lg rounded-md hidden">
                <Link href="#" className="block px-4 py-2 text-gray-700" prefetch={false}>
                  API Reference
                </Link>
                <Link href="#" className="block px-4 py-2 text-gray-700" prefetch={false}>
                  SDKs
                </Link>
              </div>
            </div>
            <Link href="#" className="text-gray-700" prefetch={false}>
              Changelog
            </Link>
            <Button variant="outline" className="ml-4">
              Cloud Portal Login
            </Button>
            <div className="relative">
              <Input type="search" placeholder="Search..." className="pl-8" />
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500" />
            </div>
          </nav>
        </div>
      </header>
      <main className="container mx-auto py-8 px-6">
        <section className="bg-black text-white p-8 rounded-md flex items-center justify-between">
          <div className="max-w-md">
            <h2 className="text-3xl font-bold">Sitecore XM Cloud Documentation</h2>
            <p className="mt-4">
              Access the latest documentation for XM Cloud, a headless, cloud-native, API-first, content and layout
              management system that can scale based on your needs.
            </p>
          </div>
          <div className="w-1/3">
            <img
              src="/placeholder.svg"
              alt="XM Cloud"
              className="rounded-md"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
          </div>
        </section>
        <section className="mt-8">
          <h3 className="text-2xl font-bold">Changelog</h3>
          <p className="mt-2 text-gray-700">Learn about new features and enhancements to Sitecore XM Cloud.</p>
        </section>
      </main>
    </div>
  )
}

function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
